# environment settings
total_timesteps: 2_000_000

# model hyperparameters
policy: MultiInputPolicy
buffer_size: 1_000_000
batch_size: 1024
gamma: 0.95
tau: 0.05
learning_rate: 0.001
action_noise_sigma: 0.1

policy_kwargs:
  n_critics: 2
  net_arch: [512, 512, 512]

# callback frequencies
eval_freq: 50_000
checkpoint_freq: 200_000

# HER parameters
replay_buffer_class: HerReplayBuffer
replay_buffer_kwargs:
  n_sampled_goal: 4
  goal_selection_strategy: future
